import type { Metadata } from "next";
import { Mandali } from "next/font/google";
import "./globals.css";
import { ReactClientQueryProvider } from "../components/ReactClientQueryProvider";
import { cn } from "@/lib/utils";
import Window from "@/components/Window";
import Channels from "@/components/Channels";
import { CounterStoreProvider } from "@/providers/CountStorageProvider";
import { CategoriesStorageProvider } from "@/providers/CategoriesStorageProvider";

const mandali = Mandali({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReactClientQueryProvider>
      <html lang="en">
        <CategoriesStorageProvider>
          <CounterStoreProvider>
            <body className={cn("h-screen max-w-[1980px] flex m-auto bg-my-gray-dark antialiased text-zinc-100", mandali.className)}>
              <Window>
                <Channels />
              </Window>
              {children}
            </body>
          </CounterStoreProvider>
        </CategoriesStorageProvider>
      </html>
    </ReactClientQueryProvider >
  );
}
