import type { Metadata } from "next";
import { Mandali } from "next/font/google";
import "./globals.css";

const mandali = Mandali({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mandali.className}>{children}</body>
    </html>
  );
}
